import os
import re


def split_html(html):

    os.makedirs("generated/css", exist_ok=True)
    os.makedirs("generated/js", exist_ok=True)
    os.makedirs("generated/assets", exist_ok=True)

    # ---------------- CSS ----------------

    css = ""

    css_match = re.search(
        r"<style>(.*?)</style>",
        html,
        re.DOTALL
    )

    if css_match:

        css = css_match.group(1)

        html = re.sub(
            r"<style>.*?</style>",
            '<link rel="stylesheet" href="css/style.css">',
            html,
            flags=re.DOTALL
        )

    # ---------------- JS ----------------

    js = ""

    js_match = re.search(
        r"<script>(.*?)</script>",
        html,
        re.DOTALL
    )

    if js_match:

        js = js_match.group(1)

        html = re.sub(
            r"<script>.*?</script>",
            '<script src="js/script.js"></script>',
            html,
            flags=re.DOTALL
        )

    with open(
        "generated/index.html",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(html)

    with open(
        "generated/css/style.css",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(css)

    with open(
        "generated/js/script.js",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(js)

    with open(
        "generated/README.md",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            "Generated by JimAI Website Generator"
        )