"""Business Profile

Revision ID: d52299cfd221
Revises: 24614e677eb4
Create Date: 2026-06-27 01:08:58.329637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52299cfd221'
down_revision = '24614e677eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('website_style', sa.String(length=255), nullable=True),
    sa.Column('color_theme', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
